sudo: true
language: android

cache:
  directories:
    - ${TRAVIS_BUILD_DIR}/gradle/caches/
    - ${TRAVIS_BUILD_DIR}/gradle/wrapper/dists/

env:
  global:
    - GRADLE_OPTS='-Dorg.gradle.daemon=false -Dorg.gradle.parallel=false -Dkotlin.incremental=false -DdisablePreDex'
    - ANDROID_TARGET=android-26
    - ANDROID_BUILD_TOOLS_VERSION=26.0.2
    - ANDROID_ABI=armeabi-v7a
    - ANDROID_EMULATOR_TARGET=android-22

android:
  components:
    - tools
    - build-tools-$ANDROID_BUILD_TOOLS_VERSION
    - $ANDROID_TARGET
    - $ANDROID_EMULATOR_TARGET
    - extra-google-google_play_services
    - extra-android-support
    - extra
    - sys-img-$ANDROID_ABI-$ANDROID_EMULATOR_TARGET

before_install:
  - echo yes | sdkmanager "platforms;$ANDROID_TARGET" "build-tools;$ANDROID_BUILD_TOOLS_VERSION"


script:
  - echo no | android create avd --force -n test -t $ANDROID_EMULATOR_TARGET --abi $ANDROID_ABI
  - emulator -avd test -no-window &
  - ./gradlew check
  - android-wait-for-emulator
  - adb shell input keyevent 82 &
  - ./gradlew connectedAndroidTest

deploy:
  provider: script
  script: ./gradlew Empyr:publish
  skip_cleanup: true

