sudo: false
language: android

android:
  - build-tools-26.0.2
  - android-26
  - extra-google-google_play_services
  - sys-img-armeabi-v7a-android-26

script: ./gradlew connectedAndroidTest

deploy:
  provider: script
  script: ./gradlew Empyr:publish
  skip_cleanup: true

